---
- name: Run User-Specified Script on All Hosts and Collect Results
  hosts: all
  gather_facts: yes
  vars:
    script_name: "{{ script_name }}"
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
    DBNAME: "{{ DBNAME }}"


  tasks:
    - name: Ensure result directory exists on the control node
      ansible.builtin.file:
        path: "{{ result_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Ensure script has execute permission
      ansible.builtin.file:
        path: "{{ playbook_dir }}/files/{{ script_name }}"
        mode: '0755'

    - name: Run the user-specified script
      ansible.builtin.shell: "{{ playbook_dir }}/files/{{ script_name }}"
      register: script_result
      ignore_errors: yes

