---
- name: Run User-Specified Script on All Hosts and Collect Results
  hosts: all
  gather_facts: no
  vars:
    script_name: "{{ script_name }}"
    #db_user: "{{ db_user }}"
    #db_password: "{{ db_password }}"
    #DBNAME: "{{ DBNAME }}"
    #DB_ROOT_PASS: "{{ DB_ROOT_PASS }}"


  tasks:
    - name: Upload the selected bash script to the host
      ansible.builtin.copy:
        src: "./files/{{ script_name }}"
        dest: "/tmp/"
        mode: '0755'


    - name: Execute the selected bash script to collect system information
      ansible.builtin.shell:
        cmd: "/tmp/{{ script_name }}"
      register: script_output

    - name: host info
      ansible.builtin.debug:
        msg: 
          - "Host: {{ inventory_hostname }}"
          - "IP: {{ ansible_ssh_host }}"

    - name: Display echo output
      ansible.builtin.debug:
        msg: "{{ script_output.stdout_lines }}"
      when: script_output.stdout_lines is defined and script_output.stdout_lines | length > 0

    - name: Display errors
      ansible.builtin.debug:
        msg: "{{ script_output.stderr_lines }}"
      when: script_output.stderr_lines is defined and script_output.stderr_lines | length > 0

    #- name: Clean up the scripts folder from the server
      #ansible.builtin.file:
        #path: /tmp/{{ script_name }}
        #state: absent          
